//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaScoutGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TVFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TVFolders"]));
            }
            set {
                this["TVFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MovieFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MovieFolders"]));
            }
            set {
                this["MovieFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} - {1}x{3} - {2}")]
        public string TVfileformat {
            get {
                return ((string)(this["TVfileformat"]));
            }
            set {
                this["TVfileformat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool forceUpdate {
            get {
                return ((bool)(this["forceUpdate"]));
            }
            set {
                this["forceUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool renameTVFiles {
            get {
                return ((bool)(this["renameTVFiles"]));
            }
            set {
                this["renameTVFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getSeasonPosters {
            get {
                return ((bool)(this["getSeasonPosters"]));
            }
            set {
                this["getSeasonPosters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool moveTVFiles {
            get {
                return ((bool)(this["moveTVFiles"]));
            }
            set {
                this["moveTVFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getEpisodePosters {
            get {
                return ((bool)(this["getEpisodePosters"]));
            }
            set {
                this["getEpisodePosters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getSeriesPosters {
            get {
                return ((bool)(this["getSeriesPosters"]));
            }
            set {
                this["getSeriesPosters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Season")]
        public string SeasonFolderName {
            get {
                return ((string)(this["SeasonFolderName"]));
            }
            set {
                this["SeasonFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".avi;.mkv;.mp4;.mpg;.mpeg;.ogm;.wmv;.divx;.dvr-ms")]
        public string allowedFileTypes {
            get {
                return ((string)(this["allowedFileTypes"]));
            }
            set {
                this["allowedFileTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".sub;.idx;.srt")]
        public string allowedSubtitles {
            get {
                return ((string)(this["allowedSubtitles"]));
            }
            set {
                this["allowedSubtitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool downloadAllTVImages {
            get {
                return ((bool)(this["downloadAllTVImages"]));
            }
            set {
                this["downloadAllTVImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string EpisodeNumZeroPadding {
            get {
                return ((string)(this["EpisodeNumZeroPadding"]));
            }
            set {
                this["EpisodeNumZeroPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string SeasonNumZeroPadding {
            get {
                return ((string)(this["SeasonNumZeroPadding"]));
            }
            set {
                this["SeasonNumZeroPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SilentMode {
            get {
                return ((bool)(this["SilentMode"]));
            }
            set {
                this["SilentMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool downloadAllTVBackdrops {
            get {
                return ((bool)(this["downloadAllTVBackdrops"]));
            }
            set {
                this["downloadAllTVBackdrops"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool downloadAllTVSeasonPosters {
            get {
                return ((bool)(this["downloadAllTVSeasonPosters"]));
            }
            set {
                this["downloadAllTVSeasonPosters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool downloadAllTVPosters {
            get {
                return ((bool)(this["downloadAllTVPosters"]));
            }
            set {
                this["downloadAllTVPosters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool downloadAllTVBanners {
            get {
                return ((bool)(this["downloadAllTVBanners"]));
            }
            set {
                this["downloadAllTVBanners"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getMoviePosters {
            get {
                return ((bool)(this["getMoviePosters"]));
            }
            set {
                this["getMoviePosters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getMovieFilePosters {
            get {
                return ((bool)(this["getMovieFilePosters"]));
            }
            set {
                this["getMovieFilePosters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool moveMovieFiles {
            get {
                return ((bool)(this["moveMovieFiles"]));
            }
            set {
                this["moveMovieFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool downloadAllMovieImages {
            get {
                return ((bool)(this["downloadAllMovieImages"]));
            }
            set {
                this["downloadAllMovieImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool downloadAllMoviePosters {
            get {
                return ((bool)(this["downloadAllMoviePosters"]));
            }
            set {
                this["downloadAllMoviePosters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool downloadAllMovieBackdrops {
            get {
                return ((bool)(this["downloadAllMovieBackdrops"]));
            }
            set {
                this["downloadAllMovieBackdrops"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}")]
        public string Moviefileformat {
            get {
                return ((string)(this["Moviefileformat"]));
            }
            set {
                this["Moviefileformat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} ({1})")]
        public string MovieDirformat {
            get {
                return ((string)(this["MovieDirformat"]));
            }
            set {
                this["MovieDirformat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool renameMovieFiles {
            get {
                return ((bool)(this["renameMovieFiles"]));
            }
            set {
                this["renameMovieFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SublightCmd {
            get {
                return ((string)(this["SublightCmd"]));
            }
            set {
                this["SublightCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool forceEnterSearchTerm {
            get {
                return ((bool)(this["forceEnterSearchTerm"]));
            }
            set {
                this["forceEnterSearchTerm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Specials")]
        public string SpecialsFolderName {
            get {
                return ((string)(this["SpecialsFolderName"]));
            }
            set {
                this["SpecialsFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableGlassFrame {
            get {
                return ((bool)(this["EnableGlassFrame"]));
            }
            set {
                this["EnableGlassFrame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool downloadAllTVSeasonBackdrops {
            get {
                return ((bool)(this["downloadAllTVSeasonBackdrops"]));
            }
            set {
                this["downloadAllTVSeasonBackdrops"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveXBMCMeta {
            get {
                return ((bool)(this["SaveXBMCMeta"]));
            }
            set {
                this["SaveXBMCMeta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveMyMoviesMeta {
            get {
                return ((bool)(this["SaveMyMoviesMeta"]));
            }
            set {
                this["SaveMyMoviesMeta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TVFSWatcher {
            get {
                return ((bool)(this["TVFSWatcher"]));
            }
            set {
                this["TVFSWatcher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool overwriteFiles {
            get {
                return ((bool)(this["overwriteFiles"]));
            }
            set {
                this["overwriteFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImagesByNameLocation {
            get {
                return ((string)(this["ImagesByNameLocation"]));
            }
            set {
                this["ImagesByNameLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveTVActors {
            get {
                return ((bool)(this["SaveTVActors"]));
            }
            set {
                this["SaveTVActors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveMovieActors {
            get {
                return ((bool)(this["SaveMovieActors"]));
            }
            set {
                this["SaveMovieActors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MovieFSWatcher {
            get {
                return ((bool)(this["MovieFSWatcher"]));
            }
            set {
                this["MovieFSWatcher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Zoom {
            get {
                return ((string)(this["Zoom"]));
            }
            set {
                this["Zoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSelectMovieTitle {
            get {
                return ((bool)(this["AutoSelectMovieTitle"]));
            }
            set {
                this["AutoSelectMovieTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SublightUsername {
            get {
                return ((string)(this["SublightUsername"]));
            }
            set {
                this["SublightUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SublightPassword {
            get {
                return ((string)(this["SublightPassword"]));
            }
            set {
                this["SublightPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sublight {
            get {
                return ((string)(this["Sublight"]));
            }
            set {
                this["Sublight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TVDropBoxLocation {
            get {
                return ((string)(this["TVDropBoxLocation"]));
            }
            set {
                this["TVDropBoxLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MovieDropBoxLocation {
            get {
                return ((string)(this["MovieDropBoxLocation"]));
            }
            set {
                this["MovieDropBoxLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\.720p\\.|\\.1080p\\.|\\.5\\.1\\.|\\.divx\\.|\\.xvid\\.|\\.dvdrip\\.|\\.dvd\\.|\\.rip\\.|\\.subs\\." +
            "|\\.upscaled\\.|\\d{4}|\\(\\w+\\)|\\[\\w+\\]|\\{\\w+\\}|\\<|\\[|\\{|\\(|\\)|\\}|\\]|\\>|\\.|\\-|\\s+")]
        public string SearchTermFilters {
            get {
                return ((string)(this["SearchTermFilters"]));
            }
            set {
                this["SearchTermFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string FilenameReplaceChar {
            get {
                return ((string)(this["FilenameReplaceChar"]));
            }
            set {
                this["FilenameReplaceChar"] = value;
            }
        }
    }
}
